### ISSUE TITLE
Weird Bug with MappingExtensions and NoteSliceVisualizer Version 1.0

### ISSUE THREAD

**Issue by JBSTheGamer** [nickyflello/BeatSaber-NoteSliceVisualizer#1]
So it only happens when i have MappingExtensions and NoteSliceVisualizer Version 1.0 installed. So when i play a song that depends on MappingExtensions. My sabers do this really weird thing that they just ghosts through some blocks. All maps that depends on MappingExtensions has that really weird thing happening of my sabers ghosting through some blocks. Some maps that depends on MappingExtensions is even worse than others and some of those others dont really show the problem very well as others. So i then removed the mod and the problem went away. Then i tried NoteSliceVisulizer Version 1.0.1 and it was fine. Then i went back to NoteSliceVisualizer Version 1.0 and then the problem reappeared. I even tried with just those 2 mods installed and yes it still had the same problem even though i removed all the other mods. I started to remove each mod till the problem went away. Then i removed NoteSliceVisualizer next and that is how i knew this mod was causing the problem only on Version 1.0. All previous versions was fine but NoteSliceVisualizer Version 1.0 had weird issues with MappingExtensions. Well that is all i had to say but i hoped this helped. The map that will show this issue the most is this one. [https://beatsaver.com/beatmap/8ac5](url). There is also some other maps that it occurs on. Like this one too. [https://beatsaver.com/beatmap/6b55](url).

**Comment by nickyflello** [comment]
I assume by "Version 1.0", you are referring to GridView version 1.0, which is an experimental version. This would make sense, as Mapping Extensions is creating notes outside the normal grid.

Thanks for the example map.

I've pushed a new release (1.0.2) that should resolve any note ghosting issues.
I'm now ignoring any notes that fall outside the normal grid indices.

If you find this to still be an issue in 1.0.2, please re-open.

**Comment by JBSTheGamer** [comment]
Ok it is fixed now just to let you know.
