### ISSUE TITLE
Possible Enhancement.  Note placement grid

### ISSUE THREAD

**Issue by sinfuljosh** [nickyflello/BeatSaber-NoteSliceVisualizer#2]
I'm not sure if this is possible with your plugin but thought it would be a great enhancement. Instead of just showing the cuts on the blocks to also include the layout and direction of the blocks to help players identify possible issues with their swings in certain directions.

There is an http overlay that does this and Ive included a 3 second clip of it to give you an example of what I am talking about. 

![notecut](https://user-images.githubusercontent.com/388123/75750354-a1ce2b00-5ce9-11ea-87a5-24a41bd726ef.gif)

**Comment by nickyflello** [comment]
In the current release, the display is already laid out into a grid.
The slice image can also be configured to be a long triangle to indicate the cut direction.

I could also include the triangle on the background block and rotate it to match the orientation of the note. This shouldn't be difficult to add.

**Comment by nickyflello** [comment]
Added note rotation with config to turn it off in release 1.0.3.
Added note arrow image with configurable alpha in release 1.0.3.

If you have any more suggestions, please let me know.
